test husky for type check

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,7 +3,12 @@
 . "$(dirname "$0")/_/husky.sh"
 
 
-echo '=== Linting, Formatting and Testing before committing ==='
+echo '*** Linting, Formatting and Testing before committing ***'
+
+
+npx tsc || (
+    echo -e '\033[0;31m❌❌❌ Failed Type check. ❌❌❌\033[0m'
+    false)
 
 npx lint-staged  || (
     echo '❌❌❌ Failed lint-staged check. ❌❌❌'
@@ -11,4 +16,4 @@ npx lint-staged  || (
 )
 
 
-echo '✅✅✅ Linting, Styling and Testing passed... This changes will be committed now. ✅✅✅'
+echo '🏹🏹 Linting, Styling and Testing passed... This changes will be committed now. 🏹🏹'
